import { Angle } from './classes/Angle';
import { BaseObject } from './classes/BaseObject';
import { Point } from './classes/Point';
import { Rectangle } from './classes/Rectangle';
import { RGBA } from './classes/RGBA';
import { Size } from './classes/Size';
import { compare } from './modules/compare';
import { funcs } from './modules/funcs';
import { numbers } from './modules/numbers';
import { randoms } from './modules/randoms';
import { web } from './modules/web';
import { AngleData } from './types/AngleData';
import { PointData } from './types/PointData';
import { RectangleData } from './types/RectangleData';
import { RGBAData } from './types/RGBAData';
import { SizeData } from './types/SizeData';
export { compare, funcs, numbers, randoms, web };
export { AngleData, PointData, RectangleData, RGBAData, SizeData };
export { Angle, BaseObject, Point, Rectangle, RGBA, Size };
